Pdf stability (#111)
* updated pdf error handling, user toast

* improved comments, removed unused statements

* improved null handling

* e to NoSuchMethodError

* removed additional unused statements

* removed additional unused statements (2)?