Additional Comments Before code freeze (#117)
* condensed whitespace, added base for references

* pdf depth scaling

* converted percent recovery to double

* updated pdf classes with new values

* updated loginfo pdf object

* pdf maps loginfo to loginfopdf

* improved pdf loginfo null handling

* updated pdf_classes loginfo to init null to n/a

* key styling

* updated negative handling, minor styling

* condensed level creation into functions

* base overflowing pdf layer trimming functionality

* pdf layer overflow functionality complete

* writes error pdf in case of error

* touched up tags

* minor tidying up styling and unused variables

* manual tag flexing

* sort levels before processing

* clear testsToDisplay at start of function call

* naming conventions

* nosuchmethoderror blocks

* added comments to main, FileHandler, ObjectHandler, and CSVExporter

Co-authored-by: jctrotter <trotterj@oregonstate.edu>